<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gsfavicon"
 *
 * Auto generated by Extension Builder 2017-02-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'GS Favicon for Bootstrap Package',
	'description' => 'GS Favicon allows you to use favicons generated at http://www.favicon-generator.org/ with the Bootstrap Package.',
	'category' => 'templates',
	'author' => 'Simon Gilli',
	'author_email' => 'typo3@gilbertsoft.org',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.9-8.99.99',
			'bootstrap_package' => '6.2.9-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);